name: Create Release as Draft

on:
  push:
    tags:
      - 'release-*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=$(echo "${GITHUB_REF_NAME}" | cut -d'-' -f2-)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create zip from dist folder
        run: |
          cd dist
          zip -r "../pos-assistant-${{ steps.extract_version.outputs.version }}.zip" .
          cd ..

      - name: Create GitHub release (draft)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ steps.extract_version.outputs.version }}
          draft: true
          prerelease: false
          files: pos-assistant-${{ steps.extract_version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
