name: Create Release as Draft

on:
  push:
    tags:
      - 'release-*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=$(echo "${GITHUB_REF_NAME}" | cut -d'-' -f2-)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create zip excluding .git and README.md
        run: |
          zip -r "pos-assistant-${{ steps.extract_version.outputs.version }}.zip" . -x ".git/*" "README.md"

      - name: Create GitHub release (draft)
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          draft: true
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pos-assistant-${{ steps.extract_version.outputs.version }}.zip
          asset_name: pos-assistant-${{ steps.extract_version.outputs.version }}.zip
          asset_content_type: application/zip
